name: Build Docker images from project

on: #[workflow_dispatch]
  push: 
    branches: 
      - main
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        docker build -t dimilan/beimage:latest ./backend
        docker build -t dimilan/feimage:latest ./frontend
    - name: Push images to DockerHub
      run: |
        docker login -u dimilan -p ${{ secrets.DOCKERHUBTOKEN }}
        docker push dimilan/feimage:latest
        docker push dimilan/beimage:latest  

